steps:
  # Deploy the Cloud Function directly from source
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions',
      'deploy',
      'batch-orchestrator',
      '--gen2',
      '--memory=512MB',
      '--cpu=1',
      '--max-instances=4',
      '--runtime=python312',
      '--project=$PROJECT_ID',
      '--region=$_REGION',
      '--source=cloud-functions/batch_orchestrator_function/src/',
      '--entry-point=batch_orchestrator',
      '--ingress-settings=internal-only',
      '--service-account=$_SERVICE_ACCOUNT',
      '--vpc-connector=bby-net1-us-central1',
      '--trigger-http',
      '--egress-settings=all',
      '--timeout=540s'
    ]
    id: deploy

# Define substitutions for configurable values
substitutions:
  _REGION: 'us-central1'
  _SERVICE_ACCOUNT: 'wf-puca-dataflow-v2-vfb6@bbyus-ana-puca-d01.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: '1200s'

